{pkgs, ...}: {
  imports = [
    ./hyprland-keybindings.nix
  ];

  programs.wofi = {
    enable = true;
  };

  home.packages = with pkgs; [wl-clipboard hyprland-autoname-workspaces];

  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    settings = {
      autogenerated = 0;

      # monitor setup
      "monitor" = "eDP-1, preferred, auto, 1";

      general = {
        gaps_in = 8;
        gaps_out = 15;

        border_size = 3;

        "col.active_border " = "0xffc8d3f5";
        "col.inactive_border " = "0xff454656";
      };

      decoration = {
        rounding = 20;
        rounding_power = 2;

        blur.enabled = false;
        shadow.enabled = false;
      };

      animations = {
        bezier = [
          "quick,0.15,0,0.1,1"
          "easeOutQuint,0.23,1,0.32,1"
          "linear,0,0,1,1"
        ];

        animation = [
          "border,1, 3, easeOutQuint"

          "workspaces,1, 1.94, quick, slide"
          "workspacesIn,1, 1.94, quick, slide"
          "workspacesOut,1, 1.94, quick, slide"

          "windows,1,3,easeOutQuint"
          "windowsIn,1,4.1,easeOutQuint,popin 87%"
          "windowsOut,1,1.49,linear, popin 87%"

          "fadeIn,1,1,linear"
          "fadeOut,1,1,linear"
        ];
      };

      misc = {
        disable_hyprland_logo = true;
        disable_splash_rendering = true;
        background_color = "0x222436";
      };

      dwindle = {
        "force_split" = 2;
      };

      # aliases
      "$mod" = "SUPER";
      "$term" = "kitty";
      "$menu" = "wofi --show drun";

      # input
      input = {
        "kb_layout" = "dk";
        "kb_options" = "caps:escape";
      };

      # environment variables
      env = [
        "XCURSOR_SIZE,36"
        "HYPRCURSOR_SIZE,36"
      ];

      # exec
      exec = [
        "pkill waybar"
        "waybar &"
        "pkill -f hyprland-autoname-workspaces"
        "hyprland-autoname-workspaces -c ~/flake/modules/hyprland/config.toml &"
      ];
    };
  };

  programs.waybar = {
    enable = true;
    settings = {
      mainBar = {
        layer = "top";
        position = "top";
        margin-top = 7;
        output = "eDP-1";
        modules-left = ["custom/nix" "hyprland/workspaces"];
        modules-right = ["group/info" "clock"];

        "group/info" = {
          orientation = "horizontal";
          modules = ["network" "pulseaudio" "battery"];
        };

        clock = {
          interval = 1;
          format = "{:%a %d. %b %H:%M}";
        };

        network = {
          format = "";
          format-wifi = "<span size='18pt' rise='-2pt' color='#ff757f'>󰖩</span>  {essid}";
          format-disconnected = "<span size='18pt' rise='-2pt'>󰖪</span>";
        };

        battery = {
          format = "<span size='18pt' rise='-2pt' color='#c3e88d'>{icon}</span> {capacity}%";
          format-icons = {
            discharging = ["󰁻" "󰁽" "󰁿" "󰂁" "󰁹"];
            charging = ["󰂆" "󰂈" "󰂉" "󰂊" "󰂅"];
          };

          interval = 60;
          states = {
            warning = 30;
            critical = 15;
          };
          tooltip = true;
          tooltip-format-charging = "{capacity}% | full in {time}";
          tooltip-format-discharging = "{capacity}% | empty in {time}";
        };

        pulseaudio = {
          format = "{icon} {volume}%";
          tooltip = true;
          tooltip-format = "volume: {volume}%";
          format-icons = {
            default = "<span size='18pt' rise='-2pt' color='#ffc777'> </span>";
            default-muted = "<span size='16pt' rise='-1pt' color='#ffc777'> </span>";
          };
        };

        "custom/nix" = {
          format = "<span size='28pt'></span>";
        };
      };

      "hyprland/workspaces" = {
        format = "{name}";
      };
    };
    # colors
    # foreground  #c8d3f5
    # comments    #636da6
    style = ''
      * {
        font-family: Liga SFMono Nerd Font;
        font-size: 20px;
        font-weight: 600;
      }

      window#waybar {
        background-color: #222436;
        color: #c8d3f5;
        border-bottom: 3px solid #454656;
      }

      #clock {
        margin: 0px 10px;
        margin-bottom: 13px;
        color: #c8d3f5;
      }

      #custom-nix {
        margin: 0px 24px;
        margin-top: -14px;
        color: #86e1fc;
      }

      #battery {
        margin-right: 6px;
      }

      #network, #pulseaudio {
        margin-right: 30px;
      }

      #info {
        background-color: #2b2c3d;
        color: #c8d3f5;
        border: 3px solid #343544;
        border-radius: 15px;
        padding: 3px 12px 3px 12px;
        margin: 0px 10px;
        margin-bottom: 13px;
      }

      #workspaces {
        margin-bottom: 13px;
      }

      #workspaces button {
        background-color: #2b2c3d;
        color: #b4bedc;
        border: 3px solid #343544;
        border-radius: 15px;
        padding: 3px 20px 3px 12px;
        margin: 0px 10px;
      }

      #workspaces button.active {
        border: 3px solid #c099ff;
        color: #c8d3f5;
      }
    '';
  };
}
