{pkgs, ...}: {
  imports = [
    ./hyprland-keybindings.nix
  ];

  programs.wofi = {
    enable = true;
  };

  home.packages = with pkgs; [wl-clipboard];

  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    settings = {
      autogenerated = 0;

      # monitor setup
      "monitor" = "eDP-1, preferred, auto, 1";

      general = {
        gaps_in = 8;
        gaps_out = 15;

        border_size = 3;

        "col.active_border " = "0xffc0caf5";
        "col.inactive_border " = "0xff636da6";
      };

      decoration = {
        rounding = 20;
        rounding_power = 2;

        blur.enabled = false;
        shadow.enabled = false;
      };

      animations = {
        bezier = [
          "quick,0.15,0,0.1,1"
          "easeOutQuint,0.23,1,0.32,1"
          "linear,0,0,1,1"
        ];

        animation = [
          "border,1, 3, easeOutQuint"

          "workspaces,1, 1.94, quick, slide"
          "workspacesIn,1, 1.94, quick, slide"
          "workspacesOut,1, 1.94, quick, slide"

          "windows,1,3,easeOutQuint"
          "windowsIn,1,4.1,easeOutQuint,popin 87%"
          "windowsOut,1,1.49,linear, popin 87%"

          "fadeIn,1,1,linear"
          "fadeOut,1,1,linear"
        ];
      };

      misc = {
        disable_hyprland_logo = true;
        disable_splash_rendering = true;
        background_color = "0x1a1b26";
      };

      dwindle = {
        "force_split" = 2;
      };

      # aliases
      "$mod" = "SUPER";
      "$term" = "kitty";
      "$menu" = "wofi --show drun";

      # input
      input = {
        "kb_layout" = "dk";
        "kb_options" = "caps:escape";
      };

      # environment variables
      env = [
        "XCURSOR_SIZE,36"
        "HYPRCURSOR_SIZE,36"
      ];

      cursor = {
        no_warps = true;
        hide_on_key_press = true;
      };

      # exec-once
      exec-once = [
        "waybar &"
      ];

      # exec
      # exec = [
      #   "pkill waybar"
      #   "waybar &"
      # ];
    };
  };

  programs.waybar = {
    enable = true;
    settings = {
      mainBar = {
        layer = "top";
        position = "top";
        margin-top = 7;
        output = "eDP-1";
        modules-left = ["custom/nix" "hyprland/workspaces"];
        modules-right = ["tray" "group/info" "clock"];

        "group/info" = {
          orientation = "horizontal";
          modules = ["network" "pulseaudio" "battery"];
        };

        tray = {
          icon-size = 24;
          spacing = 10;
        };

        clock = {
          interval = 1;
          format = "{:%a %d. %b %H:%M}";
        };

        network = {
          format = "";
          format-wifi = "<span size='18pt' rise='-2pt' color='#f7768e'>󰖩</span>  {essid}";
          format-disconnected = "<span size='18pt' rise='-2pt' color='#f7768e'>󰖪</span>  disconnected";

          max-length = 20;

          tooltip = true;
          tooltip-format-wifi = "󰤯 {signalStrength}%\n󰇚 {bandwidthDownBytes}\n󰕒 {bandwidthUpBytes}";
        };

        battery = {
          format = "<span size='18pt' rise='-2pt' color='#9ece6a'>{icon}</span> {capacity}%";
          format-icons = {
            discharging = ["󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹"];
            charging = ["󰂆" "󰂈" "󰂉" "󰂊" "󰂅"];
          };

          interval = 60;
          full-at = 98;

          states = {
            warning = 10;
          };

          format-warning = "<span size='18pt' rise='-2pt' color='#f7768e'>󰂃</span> {capacity}%";

          tooltip = true;
          tooltip-format-charging = "{capacity}% | full in {time}";
          tooltip-format-discharging = "{capacity}% | empty in {time}";
        };

        pulseaudio = {
          format = "{icon} {volume}%";
          format-bluetooth = "󰂯 {volume}%";
          tooltip = true;
          tooltip-format = "volume: {volume}%";
          format-icons = {
            default = "<span size='18pt' rise='-2pt' color='#e0af68'> </span>";
            default-muted = "<span size='16pt' rise='-1pt' color='#e0af68'> </span>";
          };
        };

        "custom/nix" = {
          format = "<span size='28pt'></span>";
        };

        "hyprland/workspaces" = {
          format = "<b>{id}</b>  {windows}";
          format-window-separator = "<span size='12pt'>  </span>";

          window-rewrite-default = "󰘔";
          window-rewrite = {
            "class<kitty>" = "";
            "class<librewolf" = "";
            "class<discord>" = "";
            "class<teams-for-linux>" = "󰊻";
            "class<.*zathura.*>" = "";
            "class<kitty> title<.*spotify.*>" = "";
          };
        };
      };
    };
    # colors
    # foreground  #c8d3f5
    # new foreground #c0caf5

    # comments    #636da6
    style = ''
      * {
        font-family: Liga SFMono Nerd Font;
        font-size: 20px;
        font-weight: 600;
      }

      window#waybar {
        background-color: #1a1b26;
        color: #c0caf5;
        border-bottom: 3px solid #636da6;
      }

      #clock {
        margin: 0px 10px;
        margin-bottom: 13px;
        color: #c0caf5;
      }

      #custom-nix {
        margin: 0px 24px;
        margin-top: -14px;
        color: #7dcfff;
      }

      #tray {
        margin: 5px 13px;
        margin-bottom: 15px;
      }

      #battery {
        margin-right: 6px;
      }

      #network, #pulseaudio {
        margin-right: 30px;
      }

      #info {
        background-color: #2b2c3d;
        color: #c0caf5;
        border: 3px solid #343544;
        border-radius: 15px;
        padding: 3px 12px 3px 12px;
        margin: 0px 10px;
        margin-bottom: 13px;
      }

      #workspaces {
        margin-bottom: 13px;
      }

      #workspaces button {
        background-color: #2b2c3d;
        color: #b4bedc;
        border: 3px solid #343544;
        border-radius: 15px;
        padding: 3px 20px 3px 12px;
        margin: 0px 10px;
      }

      #workspaces button.active {
        border: 3px solid #bb9af7;
        color: #c0caf5;
      }
    '';
  };
}
